
use_frameworks! :linkage > :static

platform :ios, '13.0'

target 'DeepmediFingerKit_Example' do
  pod 'DeepmediFingerKit', :path => '../'

	#pod 'Then'
	pod 'SnapKit', '~> 5.0.0'
	#pod 'GoogleMLKit/FaceDetection'
	#pod 'Alamofire', '~> 5.2.0'
	#pod 'OpenCV'
	#pod 'RxSwift', '~> 6.0.0'
	#pod 'RxCocoa', '~> 6.0.0'

  target 'DeepmediFingerKit_Tests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
    end
  end
end

